const sensitiveFieldNames = [
  "password",
  "Password",
  "currentPassword",
  "CurrentPassword",
  "newPassword",
  "NewPassword",
  "confirmPassword",
  "ConfirmPassword",
  "passwordHash",
  "PasswordHash",
  "token",
  "Token",
  "accessToken",
  "AccessToken",
  "refreshToken",
  "RefreshToken",
  "idToken",
  "IdToken",
  "sessionToken",
  "SessionToken",
  "apiKey",
  "ApiKey",
  "APIKey",
  "secret",
  "Secret",
  "clientSecret",
  "ClientSecret",
  "authorization",
  "Authorization",
  "cookie",
  "Cookie",
  "cookies",
  "Cookies",
] as const;

export const SENSITIVE_LOG_PATHS = [
  ...sensitiveFieldNames.flatMap((field) => [
    field,
    `*.${field}`,
    `*.*.${field}`,
    `*.*.*.${field}`,
  ]),
  "request",
  "Request",
  "req",
  "Req",
  "*.request",
  "*.Request",
  "*.req",
  "*.Req",
  "session",
  "Session",
  "*.session",
  "*.Session",
] as const;
