import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

/**
 * The secret that proves a caller is the one who asked for the upload.
 *
 * It is returned exactly once, when the intent is created, and only its SHA-256
 * hash is stored. A database dump therefore contains nothing that can finalize
 * an upload, which is the same reason a password is not stored either.
 *
 * It is deliberately not a UUID. A v4 UUID carries 122 bits, which would be
 * enough, but it also *looks* like an identifier: a value shaped like a UUID
 * tends to end up in a URL path, in a log line, or in an error message, because
 * every other UUID in the system safely does. A 256-bit base64url string does
 * not invite that.
 *
 * The token never appears in a log, in an error, in an audit record, in an
 * object key, or in a query string. The calling module sends it in a JSON body,
 * after it has authorized the caller in whatever way it sees fit — which is the
 * layering this platform depends on: the token proves *which upload*, and the
 * module proves *which user*.
 */
const TOKEN_RANDOM_BYTES = 32;

/** 32 bytes of base64url is always 43 characters. */
export const FINALIZE_TOKEN_LENGTH = 43;
const TOKEN_PATTERN = /^[A-Za-z0-9_-]{43}$/;
const TOKEN_HASH_PATTERN = /^[0-9a-f]{64}$/;

export function createFinalizeToken(): string {
  return randomBytes(TOKEN_RANDOM_BYTES).toString("base64url");
}

export function isFinalizeTokenShaped(value: unknown): value is string {
  return typeof value === "string" && TOKEN_PATTERN.test(value);
}

export function isFinalizeTokenHash(value: unknown): value is string {
  return typeof value === "string" && TOKEN_HASH_PATTERN.test(value);
}

/**
 * SHA-256, unsalted and uniterated, and that is the right choice here.
 *
 * A password needs a slow hash because it is low-entropy and human-chosen. This
 * value is 256 bits of `randomBytes`, so there is no dictionary to run and no
 * advantage to a work factor — while a slow hash on the finalize path would be
 * a cost paid on every upload, and a per-token salt would prevent the lookup by
 * hash that makes the comparison a single indexed read.
 */
export function hashFinalizeToken(token: string): string {
  return createHash("sha256").update(token, "utf8").digest("hex");
}

/**
 * Constant-time comparison of a presented token against a stored hash.
 *
 * Hashing first and comparing the digests means the comparison is over two
 * fixed-length values, so the length of the presented token leaks nothing. A
 * malformed token compares as unequal rather than throwing, because a throw on
 * "wrong shape" and a rejection on "wrong value" would be distinguishable to a
 * caller — and the whole point is that they must not be.
 */
export function finalizeTokenMatches(
  presentedToken: unknown,
  storedHash: string,
): boolean {
  if (!isFinalizeTokenShaped(presentedToken)) {
    return false;
  }

  if (!isFinalizeTokenHash(storedHash)) {
    return false;
  }

  return timingSafeEqual(
    Buffer.from(hashFinalizeToken(presentedToken), "hex"),
    Buffer.from(storedHash, "hex"),
  );
}

/**
 * The finalization lease token.
 *
 * Same construction, different purpose: this one is never handed to a client at
 * all. It is generated by an attempt that claims an intent, stored as a hash,
 * and presented by that same attempt when it completes. An attempt whose lease
 * was reclaimed presents a hash that no longer matches and writes nothing.
 */
export function createLeaseToken(): string {
  return randomBytes(TOKEN_RANDOM_BYTES).toString("base64url");
}

export const hashLeaseToken = hashFinalizeToken;
